### PR TITLE
Fix printing of TH brackets

### LINKED ISSUE #196: Declaration splices get broken sometimes
Input:

```haskell
{-# LANGUAGE TemplateHaskell #-}

$( do [d| baz = baz |] )
```

Output:

```haskell
{-# LANGUAGE TemplateHaskell #-}

$(do
  [d|baz = baz
  |])
```

```
5:3: error: …
    parse error (possibly incorrect indentation or mismatched brackets)
  |
```

### PR DESCRIPTION
**Pull request by utdemir**
Close #196

The actual solution was simply indenting the closing `|]` one more level. However there were a few more issues around them, which led me to a slightly bigger refactor.

The main reason is that, all `p_*Decl` functions used to print a trailing newline. This makes sense for top-level constructs, however it was making printing something like `[d|data Foo = Foo|]` impossible.

In this PR, I removed trailing newlines from individual printers and gave that responsibility to `p_hsDecls`, and inserted an additional trailing newline when printing modules.

While doing that, I noticed a few bugs/inconsistencies, and I had to fix them in the process:

* Warning pragmas used to not print a trailing newline, so they were always attached to the next expression. I made it more like the other pragmas, where we attach it to a neighbour function if the name matches, otherwise we separate it with a newline.
* We used to print single line GADT's and single line `do` notations using multiple lines, which breaks idempotency on some cases (formatting an already formatted output can give a different result). I tweak them to prefer single line layout if possible (sometimes it is not possible because of the semicolon syntax).

### CODE REVIEW

File: data/examples/declaration/data/gadt-syntax-out.hs [hunk 1]
```diff
@@ -1,3 +1,2 @@
 {-# LANUGAGE GADTSyntax #-}
-data Foo where
-  MKFoo :: a -> (a -> Bool) -> Foo
+data Foo where MKFoo :: a -> (a -> Bool) -> Foo
```
Comment (mrkkrp) [inline data/examples/declaration/data/gadt-syntax-out.hs]: I think we should keep the previous style because it's more readable (after all, that's the point of the tool!). Currently on `master` it works by re-formatting single version into the multi-line version without issues.

File: data/examples/declaration/warning/warning-single-line-out.hs [hunk 2]
```diff
@@ -1,4 +1,5 @@
-{-# WARNING test "This is a warning" #-}
 {-# DEPRECATED test, foo "This is a deprecation" #-}
+
+{-# WARNING test "This is a warning" #-}
```
Comment (mrkkrp) [inline data/examples/declaration/warning/warning-single-line-out.hs]: What do you check with this change? If it's just the presence of newline after deprecation annotation, then wouldn't it be already printed even without warning annotation following it? (I.e. newline would be there between deprecation annotation and `test :: IO ()`.)

File: data/examples/declaration/data/gadt-syntax-out.hs (hunk 1 above)
Comment (utdemir) [reply data/examples/declaration/data/gadt-syntax-out.hs]: In its current design, `ormolu` is not able to convert a single-line expression/statement to a multi-line one. The reason is that, since we format things differently on single line and multiple lines, if we re-format a single line-version to a multi-line one, there is a chance that we will format it differently on the next run, breaking the idempotency. As an example:


It works currently on `master` because we don't have a test where we have this problem in a nested scope. As an example, this wouldn't work on master (assuming we applied the fix for the closing bracket):

```
{-# LANGUAGE TemplateHaskell #-}

foo = [d|data Foo where MKFoo :: a -> (a -> Bool) -> Foo|]
```

Run 1:

```
{-# LANGUAGE TemplateHaskell #-}

foo = [d|data Foo where
    MKFoo :: a -> (a -> Bool) -> Foo
  |]
```

run 2:

```
{-# LANGUAGE TemplateHaskell #-}

foo = [d|
  data Foo where
    MKFoo :: a -> (a -> Bool) -> Foo
  |]
```

From ormolu's perspective, the `[d| |]` bracket in a single-line
layout on the "run 1", but on a multi-line layout on "run 2". 

There is another example of this issue in [this comment](https://github.com/tweag/ormolu/issues/258#issuecomment-519342454).

File: data/examples/declaration/warning/warning-single-line-out.hs (hunk 2 above)
Comment (utdemir) [reply data/examples/declaration/warning/warning-single-line-out.hs]: I was testing the absence of newline after the `WARNING` annotation. After this PR it's only adjacent to the `test` function because of the [line 143 
 of Declaration.hs](https://github.com/tweag/ormolu/pull/263/files#diff-0ccd0f9b89649783f9d4f7e7a6dc9e5eR143)

File: data/examples/declaration/data/gadt-syntax-out.hs (hunk 1 above)
Comment (mrkkrp) [reply data/examples/declaration/data/gadt-syntax-out.hs]: This makes sense to me, thanks for the explanation.

File: data/examples/declaration/warning/warning-single-line-out.hs (hunk 2 above)
Comment (mrkkrp) [reply data/examples/declaration/warning/warning-single-line-out.hs]: I think we can keep it "as is".
