### PR TITLE
Default fixity to infixl 9

### LINKED ISSUE #907: Style regression with backticks
Mixing backtick-ed functions with ordinary infix operators often looks worse than it used to. This is presumably a victim of the fixity overhaul.

Ormolu 0.4:
```hs
def1 =
  (,,)
    <$> gvar (primitiveGVar "natToHex")
      `app` ne
    <*> con cNothing
      `aPP` tcon tChar

def2 =
  tds1
    && lc1 == mempty
    && gc1 `M.isSubmapOf` gc2
    && sh1 == sh2
```

Ormolu 0.5:
```hs
def1 =
  (,,)
    <$> gvar (primitiveGVar "natToHex")
    `app` ne
    <*> con cNothing
    `aPP` tcon tChar

def2 =
  tds1
    && lc1
    == mempty
    && gc1
    `M.isSubmapOf` gc2
    && sh1
    == sh2
```

### PR DESCRIPTION
**Pull request by mrkkrp**
Close #907.

### CODE REVIEW

File: data/examples/declaration/value/function/infix/op-chain-r-eq-dollar-2-out.hs [hunk 1]
```diff
@@ -1,11 +1,11 @@
...
-              7 `seq`
-                8
+  1
+    `seq` 2
+    `seq` 3
+    `seq` 4
+    $ 5
+      `seq` 6
+      `seq` 7
+      `seq` 8
```
Comment (tbagrel1) [inline data/examples/declaration/value/function/infix/op-chain-r-eq-dollar-2-out.hs:11]: `seq` is available in Base: https://hackage.haskell.org/package/base-4.17.0.0/docs/doc-index-S.html and has `infixr 0` fixity, so this example shouldn't change IMO.

**Review by tbagrel1 — COMMENTED** [review]
Shouldn't we extend this change to all unknown operators, not just backticked ones?

File: data/examples/declaration/value/function/infix/op-chain-r-eq-dollar-2-out.hs (hunk 1 above)
Comment (mrkkrp) [reply data/examples/declaration/value/function/infix/op-chain-r-eq-dollar-2-out.hs:11]: Yeah, I already noticed this. Will push a fix shortly.

**Review by amesgen — APPROVED** [review]
